import { z } from "zod";

export const bjcpSubcategories = [
  {
    categoryCode: "1",
    categoryName: "Standard American Beer",
    subcategoryCode: "1A",
    subcategoryName: "American Light Lager",
    doc: "https://www.bjcp.org/style/2021/1/1A/american-light-lager/",
  },
  {
    categoryCode: "1",
    categoryName: "Standard American Beer",
    subcategoryCode: "1B",
    subcategoryName: "American Lager",
    doc: "https://www.bjcp.org/style/2021/1/1B/american-lager/",
  },
  {
    categoryCode: "1",
    categoryName: "Standard American Beer",
    subcategoryCode: "1C",
    subcategoryName: "Cream Ale",
    doc: "https://www.bjcp.org/style/2021/1/1C/cream-ale/",
  },
  {
    categoryCode: "1",
    categoryName: "Standard American Beer",
    subcategoryCode: "1D",
    subcategoryName: "American Wheat Beer",
    doc: "https://www.bjcp.org/style/2021/1/1D/american-wheat-beer/",
  },
  {
    categoryCode: "2",
    categoryName: "International Lager",
    subcategoryCode: "2A",
    subcategoryName: "International Pale Lager",
    doc: "https://www.bjcp.org/style/2021/2/2A/international-pale-lager/",
  },
  {
    categoryCode: "2",
    categoryName: "International Lager",
    subcategoryCode: "2B",
    subcategoryName: "International Amber Lager",
    doc: "https://www.bjcp.org/style/2021/2/2B/international-amber-lager/",
  },
  {
    categoryCode: "2",
    categoryName: "International Lager",
    subcategoryCode: "2C",
    subcategoryName: "International Dark Lager",
    doc: "https://www.bjcp.org/style/2021/2/2C/international-dark-lager/",
  },
  {
    categoryCode: "3",
    categoryName: "Czech Lager",
    subcategoryCode: "3A",
    subcategoryName: "Czech Pale Lager",
    doc: "https://www.bjcp.org/style/2021/3/3A/czech-pale-lager/",
  },
  {
    categoryCode: "3",
    categoryName: "Czech Lager",
    subcategoryCode: "3B",
    subcategoryName: "Czech Premium Pale Lager",
    doc: "https://www.bjcp.org/style/2021/3/3B/czech-premium-pale-lager/",
  },
  {
    categoryCode: "3",
    categoryName: "Czech Lager",
    subcategoryCode: "3C",
    subcategoryName: "Czech Amber Lager",
    doc: "https://www.bjcp.org/style/2021/3/3C/czech-amber-lager/",
  },
  {
    categoryCode: "3",
    categoryName: "Czech Lager",
    subcategoryCode: "3D",
    subcategoryName: "Czech Dark Lager",
    doc: "https://www.bjcp.org/style/2021/3/3D/czech-dark-lager/",
  },
  {
    categoryCode: "4",
    categoryName: "Pale Malty European Lager",
    subcategoryCode: "4A",
    subcategoryName: "Munich Helles",
    doc: "https://www.bjcp.org/style/2021/4/4A/munich-helles/",
  },
  {
    categoryCode: "4",
    categoryName: "Pale Malty European Lager",
    subcategoryCode: "4B",
    subcategoryName: "Festbier",
    doc: "https://www.bjcp.org/style/2021/4/4B/festbier/",
  },
  {
    categoryCode: "4",
    categoryName: "Pale Malty European Lager",
    subcategoryCode: "4C",
    subcategoryName: "Helles Bock",
    doc: "https://www.bjcp.org/style/2021/4/4C/helles-bock/",
  },
  {
    categoryCode: "5",
    categoryName: "Pale Bitter European Beer",
    subcategoryCode: "5A",
    subcategoryName: "German Leichtbier",
    doc: "https://www.bjcp.org/style/2021/5/5A/german-leichtbier/",
  },
  {
    categoryCode: "5",
    categoryName: "Pale Bitter European Beer",
    subcategoryCode: "5B",
    subcategoryName: "Kölsch",
    doc: "https://www.bjcp.org/style/2021/5/5B/kolsch/",
  },
  {
    categoryCode: "5",
    categoryName: "Pale Bitter European Beer",
    subcategoryCode: "5C",
    subcategoryName: "German Helles Exportbier",
    doc: "https://www.bjcp.org/style/2021/5/5C/german-helles-exportbier/",
  },
  {
    categoryCode: "5",
    categoryName: "Pale Bitter European Beer",
    subcategoryCode: "5D",
    subcategoryName: "German Pils",
    doc: "https://www.bjcp.org/style/2021/5/5D/german-pils/",
  },
  {
    categoryCode: "6",
    categoryName: "Amber Malty European Lager",
    subcategoryCode: "6A",
    subcategoryName: "Märzen",
    doc: "https://www.bjcp.org/style/2021/6/6A/marzen/",
  },
  {
    categoryCode: "6",
    categoryName: "Amber Malty European Lager",
    subcategoryCode: "6B",
    subcategoryName: "Rauchbier",
    doc: "https://www.bjcp.org/style/2021/6/6B/rauchbier/",
  },
  {
    categoryCode: "6",
    categoryName: "Amber Malty European Lager",
    subcategoryCode: "6C",
    subcategoryName: "Dunkles Bock",
    doc: "https://www.bjcp.org/style/2021/6/6C/dunkles-bock/",
  },
  {
    categoryCode: "7",
    categoryName: "Amber Bitter European Beer",
    subcategoryCode: "7A",
    subcategoryName: "Vienna Lager",
    doc: "https://www.bjcp.org/style/2021/7/7A/vienna-lager/",
  },
  {
    categoryCode: "7",
    categoryName: "Amber Bitter European Beer",
    subcategoryCode: "7B",
    subcategoryName: "Altbier",
    doc: "https://www.bjcp.org/style/2021/7/7B/altbier/",
  },
  {
    categoryCode: "7",
    categoryName: "Amber Bitter European Beer",
    subcategoryCode: "7C",
    subcategoryName: "Kellerbier",
    doc: "https://www.bjcp.org/style/2015/7/7C/kellerbier/",
  },
  {
    categoryCode: "8",
    categoryName: "Dark European Lager",
    subcategoryCode: "8A",
    subcategoryName: "Munich Dunkel",
    doc: "https://www.bjcp.org/style/2021/8/8A/munich-dunkel/",
  },
  {
    categoryCode: "8",
    categoryName: "Dark European Lager",
    subcategoryCode: "8B",
    subcategoryName: "Schwarzbier",
    doc: "https://www.bjcp.org/style/2021/8/8B/schwarzbier/",
  },
  {
    categoryCode: "9",
    categoryName: "Strong European Beer",
    subcategoryCode: "9A",
    subcategoryName: "Doppelbock",
    doc: "https://www.bjcp.org/style/2021/9/9A/doppelbock/",
  },
  {
    categoryCode: "9",
    categoryName: "Strong European Beer",
    subcategoryCode: "9B",
    subcategoryName: "Eisbock",
    doc: "https://www.bjcp.org/style/2021/9/9B/eisbock/",
  },
  {
    categoryCode: "9",
    categoryName: "Strong European Beer",
    subcategoryCode: "9C",
    subcategoryName: "Baltic Porter",
    doc: "https://www.bjcp.org/style/2021/9/9C/baltic-porter/",
  },
  {
    categoryCode: "10",
    categoryName: "German Wheat Beer",
    subcategoryCode: "10A",
    subcategoryName: "Weissbier",
    doc: "https://www.bjcp.org/style/2021/10/10A/weissbier/",
  },
  {
    categoryCode: "10",
    categoryName: "German Wheat Beer",
    subcategoryCode: "10B",
    subcategoryName: "Dunkles Weissbier",
    doc: "https://www.bjcp.org/style/2021/10/10B/dunkles-weissbier/",
  },
  {
    categoryCode: "10",
    categoryName: "German Wheat Beer",
    subcategoryCode: "10C",
    subcategoryName: "Weizenbock",
    doc: "https://www.bjcp.org/style/2021/10/10C/weizenbock/",
  },
  {
    categoryCode: "11",
    categoryName: "British Bitter",
    subcategoryCode: "11A",
    subcategoryName: "Ordinary Bitter",
    doc: "https://www.bjcp.org/style/2021/11/11A/ordinary-bitter/",
  },
  {
    categoryCode: "11",
    categoryName: "British Bitter",
    subcategoryCode: "11B",
    subcategoryName: "Best Bitter",
    doc: "https://www.bjcp.org/style/2021/11/11B/best-bitter/",
  },
  {
    categoryCode: "11",
    categoryName: "British Bitter",
    subcategoryCode: "11C",
    subcategoryName: "Strong Bitter",
    doc: "https://www.bjcp.org/style/2021/11/11C/strong-bitter/",
  },
  {
    categoryCode: "12",
    categoryName: "Pale Commonwealth Beer",
    subcategoryCode: "12A",
    subcategoryName: "British Golden Ale",
    doc: "https://www.bjcp.org/style/2021/12/12A/british-golden-ale/",
  },
  {
    categoryCode: "12",
    categoryName: "Pale Commonwealth Beer",
    subcategoryCode: "12B",
    subcategoryName: "Australian Sparkling Ale",
    doc: "https://www.bjcp.org/style/2021/12/12B/australian-sparkling-ale/",
  },
  {
    categoryCode: "12",
    categoryName: "Pale Commonwealth Beer",
    subcategoryCode: "12C",
    subcategoryName: "English IPA",
    doc: "https://www.bjcp.org/style/2021/12/12C/english-ipa/",
  },
  {
    categoryCode: "13",
    categoryName: "Brown British Beer",
    subcategoryCode: "13A",
    subcategoryName: "Dark Mild",
    doc: "https://www.bjcp.org/style/2021/13/13A/dark-mild/",
  },
  {
    categoryCode: "13",
    categoryName: "Brown British Beer",
    subcategoryCode: "13B",
    subcategoryName: "British Brown Ale",
    doc: "https://www.bjcp.org/style/2021/13/13B/british-brown-ale/",
  },
  {
    categoryCode: "13",
    categoryName: "Brown British Beer",
    subcategoryCode: "13C",
    subcategoryName: "English Porter",
    doc: "https://www.bjcp.org/style/2021/13/13C/english-porter/",
  },
  {
    categoryCode: "14",
    categoryName: "Scottish Ale",
    subcategoryCode: "14A",
    subcategoryName: "Scottish Light",
    doc: "https://www.bjcp.org/style/2021/14/14A/scottish-light/",
  },
  {
    categoryCode: "14",
    categoryName: "Scottish Ale",
    subcategoryCode: "14B",
    subcategoryName: "Scottish Heavy",
    doc: "https://www.bjcp.org/style/2021/14/14B/scottish-heavy/",
  },
  {
    categoryCode: "14",
    categoryName: "Scottish Ale",
    subcategoryCode: "14C",
    subcategoryName: "Scottish Export",
    doc: "https://www.bjcp.org/style/2021/14/14C/scottish-export/",
  },
  {
    categoryCode: "15",
    categoryName: "Irish Beer",
    subcategoryCode: "15A",
    subcategoryName: "Irish Red Ale",
    doc: "https://www.bjcp.org/style/2021/15/15A/irish-red-ale/",
  },
  {
    categoryCode: "15",
    categoryName: "Irish Beer",
    subcategoryCode: "15B",
    subcategoryName: "Irish Stout",
    doc: "https://www.bjcp.org/style/2021/15/15B/irish-stout/",
  },
  {
    categoryCode: "15",
    categoryName: "Irish Beer",
    subcategoryCode: "15C",
    subcategoryName: "Irish Extra Stout",
    doc: "https://www.bjcp.org/style/2021/15/15C/irish-extra-stout/",
  },
  {
    categoryCode: "16",
    categoryName: "Dark British Beer",
    subcategoryCode: "16A",
    subcategoryName: "Sweet Stout",
    doc: "https://www.bjcp.org/style/2021/16/16A/sweet-stout/",
  },
  {
    categoryCode: "16",
    categoryName: "Dark British Beer",
    subcategoryCode: "16B",
    subcategoryName: "Oatmeal Stout",
    doc: "https://www.bjcp.org/style/2021/16/16B/oatmeal-stout/",
  },
  {
    categoryCode: "16",
    categoryName: "Dark British Beer",
    subcategoryCode: "16C",
    subcategoryName: "Tropical Stout",
    doc: "https://www.bjcp.org/style/2021/16/16C/tropical-stout/",
  },
  {
    categoryCode: "16",
    categoryName: "Dark British Beer",
    subcategoryCode: "16D",
    subcategoryName: "Foreign Extra Stout",
    doc: "https://www.bjcp.org/style/2021/16/16D/foreign-extra-stout/",
  },
  {
    categoryCode: "17",
    categoryName: "Strong British Ale",
    subcategoryCode: "17A",
    subcategoryName: "British Strong Ale",
    doc: "https://www.bjcp.org/style/2021/17/17A/british-strong-ale/",
  },
  {
    categoryCode: "17",
    categoryName: "Strong British Ale",
    subcategoryCode: "17B",
    subcategoryName: "Old Ale",
    doc: "https://www.bjcp.org/style/2021/17/17B/old-ale/",
  },
  {
    categoryCode: "17",
    categoryName: "Strong British Ale",
    subcategoryCode: "17C",
    subcategoryName: "Wee Heavy",
    doc: "https://www.bjcp.org/style/2021/17/17C/wee-heavy/",
  },
  {
    categoryCode: "17",
    categoryName: "Strong British Ale",
    subcategoryCode: "17D",
    subcategoryName: "English Barleywine",
    doc: "https://www.bjcp.org/style/2021/17/17D/english-barleywine/",
  },
  {
    categoryCode: "18",
    categoryName: "Pale American Ale",
    subcategoryCode: "18A",
    subcategoryName: "Blonde Ale",
    doc: "https://www.bjcp.org/style/2021/18/18A/blonde-ale/",
  },
  {
    categoryCode: "18",
    categoryName: "Pale American Ale",
    subcategoryCode: "18B",
    subcategoryName: "American Pale Ale",
    doc: "https://www.bjcp.org/style/2021/18/18B/american-pale-ale/",
  },
  {
    categoryCode: "19",
    categoryName: "Amber and Brown American Beer",
    subcategoryCode: "19A",
    subcategoryName: "American Amber Ale",
    doc: "https://www.bjcp.org/style/2021/19/19A/american-amber-ale/",
  },
  {
    categoryCode: "19",
    categoryName: "Amber and Brown American Beer",
    subcategoryCode: "19B",
    subcategoryName: "California Common",
    doc: "https://www.bjcp.org/style/2021/19/19B/california-common/",
  },
  {
    categoryCode: "19",
    categoryName: "Amber and Brown American Beer",
    subcategoryCode: "19C",
    subcategoryName: "American Brown Ale",
    doc: "https://www.bjcp.org/style/2021/19/19C/american-brown-ale/",
  },
  {
    categoryCode: "20",
    categoryName: "American Porter and Stout",
    subcategoryCode: "20A",
    subcategoryName: "American Porter",
    doc: "https://www.bjcp.org/style/2021/20/20A/american-porter/",
  },
  {
    categoryCode: "20",
    categoryName: "American Porter and Stout",
    subcategoryCode: "20B",
    subcategoryName: "American Stout",
    doc: "https://www.bjcp.org/style/2021/20/20B/american-stout/",
  },
  {
    categoryCode: "20",
    categoryName: "American Porter and Stout",
    subcategoryCode: "20C",
    subcategoryName: "Imperial Stout",
    doc: "https://www.bjcp.org/style/2021/20/20C/imperial-stout/",
  },
  {
    categoryCode: "21",
    categoryName: "IPA",
    subcategoryCode: "21A",
    subcategoryName: "American IPA",
    doc: "https://www.bjcp.org/style/2021/21/21A/american-ipa/",
  },
  {
    categoryCode: "21",
    categoryName: "IPA",
    subcategoryCode: "21B",
    subcategoryName: "Specialty IPA",
    doc: "https://www.bjcp.org/style/2021/21/21B/specialty-ipa/",
  },
  {
    categoryCode: "21",
    categoryName: "IPA",
    subcategoryCode: "21C",
    subcategoryName: "Hazy IPA",
    doc: "https://www.bjcp.org/style/2021/21/21C/hazy-ipa/",
  },
  {
    categoryCode: "22",
    categoryName: "Strong American Ale",
    subcategoryCode: "22A",
    subcategoryName: "Double IPA",
    doc: "https://www.bjcp.org/style/2021/22/22A/double-ipa/",
  },
  {
    categoryCode: "22",
    categoryName: "Strong American Ale",
    subcategoryCode: "22B",
    subcategoryName: "American Strong Ale",
    doc: "https://www.bjcp.org/style/2021/22/22B/american-strong-ale/",
  },
  {
    categoryCode: "22",
    categoryName: "Strong American Ale",
    subcategoryCode: "22C",
    subcategoryName: "American Barleywine",
    doc: "https://www.bjcp.org/style/2021/22/22C/american-barleywine/",
  },
  {
    categoryCode: "22",
    categoryName: "Strong American Ale",
    subcategoryCode: "22D",
    subcategoryName: "Wheatwine",
    doc: "https://www.bjcp.org/style/2021/22/22D/wheatwine/",
  },
  {
    categoryCode: "23",
    categoryName: "European Sour Ale",
    subcategoryCode: "23A",
    subcategoryName: "Berliner Weisse",
    doc: "https://www.bjcp.org/style/2021/23/23A/berliner-weisse/",
  },
  {
    categoryCode: "23",
    categoryName: "European Sour Ale",
    subcategoryCode: "23B",
    subcategoryName: "Flanders Red Ale",
    doc: "https://www.bjcp.org/style/2021/23/23B/flanders-red-ale/",
  },
  {
    categoryCode: "23",
    categoryName: "European Sour Ale",
    subcategoryCode: "23C",
    subcategoryName: "Oud Bruin",
    doc: "https://www.bjcp.org/style/2021/23/23C/oud-bruin/",
  },
  {
    categoryCode: "23",
    categoryName: "European Sour Ale",
    subcategoryCode: "23D",
    subcategoryName: "Lambic",
    doc: "https://www.bjcp.org/style/2021/23/23D/lambic/",
  },
  {
    categoryCode: "23",
    categoryName: "European Sour Ale",
    subcategoryCode: "23E",
    subcategoryName: "Gueuze",
    doc: "https://www.bjcp.org/style/2021/23/23E/gueuze/",
  },
  {
    categoryCode: "23",
    categoryName: "European Sour Ale",
    subcategoryCode: "23F",
    subcategoryName: "Fruit Lambic",
    doc: "https://www.bjcp.org/style/2021/23/23F/fruit-lambic/",
  },
  {
    categoryCode: "23",
    categoryName: "European Sour Ale",
    subcategoryCode: "23G",
    subcategoryName: "Gose",
    doc: "https://www.bjcp.org/style/2021/23/23G/gose/",
  },
  {
    categoryCode: "24",
    categoryName: "Belgian Ale",
    subcategoryCode: "24A",
    subcategoryName: "Witbier",
    doc: "https://www.bjcp.org/style/2021/24/24A/witbier/",
  },
  {
    categoryCode: "24",
    categoryName: "Belgian Ale",
    subcategoryCode: "24B",
    subcategoryName: "Belgian Pale Ale",
    doc: "https://www.bjcp.org/style/2021/24/24B/belgian-pale-ale/",
  },
  {
    categoryCode: "24",
    categoryName: "Belgian Ale",
    subcategoryCode: "24C",
    subcategoryName: "Bière de Garde",
    doc: "https://www.bjcp.org/style/2021/24/24C/biere-de-garde/",
  },
  {
    categoryCode: "25",
    categoryName: "Strong Belgian Ale",
    subcategoryCode: "25A",
    subcategoryName: "Belgian Blond Ale",
    doc: "https://www.bjcp.org/style/2021/25/25A/belgian-blond-ale/",
  },
  {
    categoryCode: "25",
    categoryName: "Strong Belgian Ale",
    subcategoryCode: "25B",
    subcategoryName: "Saison",
    doc: "https://www.bjcp.org/style/2021/25/25B/saison/",
  },
  {
    categoryCode: "25",
    categoryName: "Strong Belgian Ale",
    subcategoryCode: "25C",
    subcategoryName: "Belgian Golden Strong Ale",
    doc: "https://www.bjcp.org/style/2021/25/25C/belgian-golden-strong-ale/",
  },
  {
    categoryCode: "26",
    categoryName: "Monastic Ale",
    subcategoryCode: "26A",
    subcategoryName: "Belgian Single",
    doc: "https://www.bjcp.org/style/2021/26/26A/belgian-single/",
  },
  {
    categoryCode: "26",
    categoryName: "Monastic Ale",
    subcategoryCode: "26B",
    subcategoryName: "Belgian Dubbel",
    doc: "https://www.bjcp.org/style/2021/26/26B/belgian-dubbel/",
  },
  {
    categoryCode: "26",
    categoryName: "Monastic Ale",
    subcategoryCode: "26C",
    subcategoryName: "Belgian Tripel",
    doc: "https://www.bjcp.org/style/2021/26/26C/belgian-tripel/",
  },
  {
    categoryCode: "26",
    categoryName: "Monastic Ale",
    subcategoryCode: "26D",
    subcategoryName: "Belgian Dark Strong Ale",
    doc: "https://www.bjcp.org/style/2021/26/26D/belgian-dark-strong-ale/",
  },
  {
    categoryCode: "27",
    categoryName: "Historical Beer",
    subcategoryCode: "27A",
    subcategoryName: "Historical Beer",
    doc: "https://www.bjcp.org/style/2021/27/27A/",
  },
  {
    categoryCode: "28",
    categoryName: "American Wild Ale",
    subcategoryCode: "28A",
    subcategoryName: "Brett Beer",
    doc: "https://www.bjcp.org/style/2021/28/28A/brett-beer/",
  },
  {
    categoryCode: "28",
    categoryName: "American Wild Ale",
    subcategoryCode: "28B",
    subcategoryName: "Mixed-Fermentation Sour Beer",
    doc: "https://www.bjcp.org/style/2021/28/28B/mixed-fermentation-sour-beer/",
  },
  {
    categoryCode: "28",
    categoryName: "American Wild Ale",
    subcategoryCode: "28C",
    subcategoryName: "Wild Specialty Beer",
    doc: "https://www.bjcp.org/style/2021/28/28C/wild-specialty-beer/",
  },
  {
    categoryCode: "28",
    categoryName: "American Wild Ale",
    subcategoryCode: "28D",
    subcategoryName: "Straight Sour Beer",
    doc: "https://www.bjcp.org/style/2021/28/28D/straight-sour-beer/",
  },
  {
    categoryCode: "29",
    categoryName: "Fruit Beer",
    subcategoryCode: "29A",
    subcategoryName: "Fruit Beer",
    doc: "https://www.bjcp.org/style/2021/29/29A/fruit-beer/",
  },
  {
    categoryCode: "29",
    categoryName: "Fruit Beer",
    subcategoryCode: "29B",
    subcategoryName: "Fruit and Spice Beer",
    doc: "https://www.bjcp.org/style/2021/29/29B/fruit-and-spice-beer/",
  },
  {
    categoryCode: "29",
    categoryName: "Fruit Beer",
    subcategoryCode: "29C",
    subcategoryName: "Specialty Fruit Beer",
    doc: "https://www.bjcp.org/style/2021/29/29C/specialty-fruit-beer/",
  },
  {
    categoryCode: "29",
    categoryName: "Fruit Beer",
    subcategoryCode: "29D",
    subcategoryName: "Grape Ale",
    doc: "https://www.bjcp.org/style/2021/29/29D/grape-ale/",
  },
  {
    categoryCode: "30",
    categoryName: "Spiced Beer",
    subcategoryCode: "30A",
    subcategoryName: "Spice, Herb, or Vegetable Beer",
    doc: "https://www.bjcp.org/style/2021/30/30A/spice-herb-or-vegetable-beer/",
  },
  {
    categoryCode: "30",
    categoryName: "Spiced Beer",
    subcategoryCode: "30B",
    subcategoryName: "Autumn Seasonal Beer",
    doc: "https://www.bjcp.org/style/2021/30/30B/autumn-seasonal-beer/",
  },
  {
    categoryCode: "30",
    categoryName: "Spiced Beer",
    subcategoryCode: "30C",
    subcategoryName: "Winter Seasonal Beer",
    doc: "https://www.bjcp.org/style/2021/30/30C/winter-seasonal-beer/",
  },
  {
    categoryCode: "30",
    categoryName: "Spiced Beer",
    subcategoryCode: "30D",
    subcategoryName: "Specialty Spice Beer",
    doc: "https://www.bjcp.org/style/2021/30/30D/specialty-spice-beer/",
  },
  {
    categoryCode: "31",
    categoryName: "Alternative Fermentables Beer",
    subcategoryCode: "31A",
    subcategoryName: "Alternative Grain Beer",
    doc: "https://www.bjcp.org/style/2021/31/31A/alternative-grain-beer/",
  },
  {
    categoryCode: "31",
    categoryName: "Alternative Fermentables Beer",
    subcategoryCode: "31B",
    subcategoryName: "Alternative Sugar Beer",
    doc: "https://www.bjcp.org/style/2021/31/31B/alternative-sugar-beer/",
  },
  {
    categoryCode: "32",
    categoryName: "Smoked Beer",
    subcategoryCode: "32A",
    subcategoryName: "Classic Style Smoked Beer",
    doc: "https://www.bjcp.org/style/2021/32/32A/classic-style-smoked-beer/",
  },
  {
    categoryCode: "32",
    categoryName: "Smoked Beer",
    subcategoryCode: "32B",
    subcategoryName: "Specialty Smoked Beer",
    doc: "https://www.bjcp.org/style/2021/32/32B/specialty-smoked-beer/",
  },
  {
    categoryCode: "33",
    categoryName: "Wood Beer",
    subcategoryCode: "33A",
    subcategoryName: "Wood-Aged Beer",
    doc: "https://www.bjcp.org/style/2021/33/33A/wood-aged-beer/",
  },
  {
    categoryCode: "33",
    categoryName: "Wood Beer",
    subcategoryCode: "33B",
    subcategoryName: "Specialty Wood-Aged Beer",
    doc: "https://www.bjcp.org/style/2021/33/33B/specialty-wood-aged-beer/",
  },
  {
    categoryCode: "34",
    categoryName: "Specialty Beer",
    subcategoryCode: "34A",
    subcategoryName: "Commercial Specialty Beer",
    doc: "https://www.bjcp.org/style/2021/34/34A/commercial-specialty-beer/",
  },
  {
    categoryCode: "34",
    categoryName: "Specialty Beer",
    subcategoryCode: "34B",
    subcategoryName: "Mixed-Style Beer",
    doc: "https://www.bjcp.org/style/2021/34/34B/mixed-style-beer/",
  },
  {
    categoryCode: "34",
    categoryName: "Specialty Beer",
    subcategoryCode: "34C",
    subcategoryName: "Experimental Beer",
    doc: "https://www.bjcp.org/style/2021/34/34C/experimental-beer/",
  },
  {
    categoryCode: "999",
    categoryName: "未分类",
    subcategoryCode: "999",
    subcategoryName: "未分类",
  },
] as const;

export const bjcpSubcategoryCodeSchema = z.enum(
  bjcpSubcategories.map((style) => style.subcategoryCode) as [
    (typeof bjcpSubcategories)[number]["subcategoryCode"],
    ...(typeof bjcpSubcategories)[number]["subcategoryCode"][],
  ]
);

export const bjcpStyleSnapshotSchema = z.object({
  bjcpCategoryCode: z.string().min(1),
  bjcpCategoryName: z.string().min(1),
  bjcpSubcategoryCode: z.string().min(1),
  bjcpSubcategoryName: z.string().min(1),
});

export function findBjcpSubcategory(code: string) {
  return bjcpSubcategories.find((style) => style.subcategoryCode === code) ?? null;
}
